### ISSUE TITLE
[feat] Add onTap & onLongPress callback

### ISSUE THREAD

**Issue by hsul4n** [vi-k/bubble#16]
Looks great to implement `onTap` & `onLongPress` to handle click action.

For example:
```
Bubble(
  onTap: () {
    print('Hello from onTap');
  },
  onLongPress: () {
    print('Hello from onLongPress');
  },
  // .. other properties
),
```

**Comment by vi-k** [comment]
I'm not sure that's a good idea. Use GestureDetector!

**Comment by shinriyo** [comment]
@hsul4n did you resolve?

**Comment by hsul4n** [comment]
> @hsul4n did you resolve?

as @vi-k says ```GestureDetector``` works like charm!
