### ISSUE TITLE
Add custom key

### ISSUE THREAD

**Issue by facuparedes** [vi-k/bubble#22]
Hi! I'm using [GetX](https://github.com/jonataslaw/getx) with a ListView.builder to add a list of bubble messages in realtime. However, when Getx rebuild ListView, some "Bubble's widget" are not refreshing and lose its nip (it changes nip direction). However, I did a temporal fix adding a UniqueKey() on a parent container, just like this:

```
return Container(
      key: UniqueKey(),
      child: Bubble(
          ...
        ),
      ),
    )
```
Right now, that works like a charm. So, can you add a "key" parameter? Thanks u!

**Comment by allanwolski** [comment]
Same here with Bloc.

**Comment by vi-k** [comment]
See 1.2.1. Please, check it.
