### ISSUE TITLE
Add null safety

### ISSUE THREAD

**Issue by JulianAssmann** [vi-k/bubble#27]
It would be great to have [null safety](https://flutter.dev/docs/null-safety) for this plugin (see [migration guide](https://dart.dev/null-safety/migration-guide)).

**Comment by norarrsgd** [comment]
Is this repo still active though?

**Comment by vi-k** [comment]
Published 1.2.0. See [CHANGELOG](https://github.com/vi-k/bubble/blob/master/CHANGELOG.md).
