### ISSUE TITLE
Massive reduce on performance when bubble nip is visible

### ISSUE THREAD

**Issue by ahmedNY** [vi-k/bubble#4]
```
            ListView.builder(
              itemCount: 1000,
              itemBuilder: (BuildContext context, int index) {
                return Bubble(
                  nip: BubbleNip.rightTop,
                  child: Text('TEST MESSAGE BODY #$index'),
                );
              },      
```

**Comment by vi-k** [comment]
Thanks! I'll test it.

**Comment by vi-k** [comment]
It's Flutter.

**Comment by vi-k** [comment]
`canvas.drawShadow()` is very slow with unusual `Path`.

**Comment by vi-k** [comment]
It seems to be working fine now.

**Comment by arthurpiccoli** [comment]
I've created PR #10 that aims to improve perfomance in this situation

**Comment by abdulrehmank7** [comment]
I have created the chat bubble using dart. You can easily modify according to your needs https://arkapp.medium.com/chat-bubble-widget-for-flutter-95d3bb82ddd8
